### PR TITLE
Change to user's home directory on startup

### PR DESCRIPTION
**Pull request by adamruzicka**
Requires
- https://github.com/RedHatInsights/yggdrasil/pull/85

### CODE REVIEW

**Comment by adamruzicka** [comment]
> Error: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (staticcheck)

Well, that's nice, but we're still building it with go 1.15.

**Comment by dominikh** [comment]
> Well, that's nice, but we're still building it with go 1.15.

Run `staticcheck` with the `-go 1.15` flag so that it only makes suggestions that are valid for Go 1.15.

**Review by ezr-ondrej — APPROVED** [review]
Looks sane to me :+1: Shall we merge?

**Comment by adamruzicka** [comment]
Closing this in favor of #12

**Pull request closed without merging**
