### PR TITLE
Add Packit config

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like it tries to reach out to the internet:
```
main.go:9:2: git.sr.ht/~spc/go-log@v0.0.0-20210611184941-ce2f05edb627: Get "https://proxy.golang.org/git.sr.ht/~spc/go-log/@v/v0.0.0-20210611184941-ce2f05edb627.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:48707->[::1]:53: read: connection refused
runner.go:15:2: github.com/google/uuid@v1.3.0: Get "https://proxy.golang.org/github.com/google/uuid/@v/v1.3.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:48707->[::1]:53: read: connection refused
external_communication.go:6:2: github.com/redhatinsights/yggdrasil@v0.0.0-20210811162724-41397343c25b: Get "https://proxy.golang.org/github.com/redhatinsights/yggdrasil/@v/v0.0.0-20210811162724-41397343c25b.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:38776->[::1]:53: read: connection refused
external_communication.go:7:2: google.golang.org/grpc@v1.58.3: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.58.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:38776->[::1]:53: read: connection refused
external_communication.go:8:2: google.golang.org/grpc@v1.58.3: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.58.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:38776->[::1]:53: read: connection refused
```

Looks like we need to run `make distribution-tarball` to create the source.

**Comment by subpop** [comment]
We're using packit for all our projects. You can see an example of a worker using meson [here](https://github.com/RedHatInsights/yggdrasil-worker-package-manager/blob/main/.packit.yaml) and a project using a plain Makefile [here](https://github.com/RedHatInsights/rhc/blob/main/.packit.yml).

**Comment by ekohl** [comment]
Build passed, squashed all commit now.

**Comment by adamruzicka** [comment]
rhel7 seems to have too old go

**Comment by ekohl** [comment]
Oh yes, we depended on EPEL for a newer golang but EPEL 7 has been archived. Should we simply drop EL 7?

**Comment by adamruzicka** [comment]
> Should we simply drop EL 7?

I'd vote for dropping it

**Comment by ekohl** [comment]
I don't know if it works, but by using the `epel-7` target it may work.

**Comment by ekohl** [comment]
@adamruzicka it's now green so this works for now. I also opened https://github.com/theforeman/foreman-packaging/pull/11110 to see if we want to maintain EL7 builds. With a downstream perspective we'll probably need to for some time and it's probably very easy to start relying on newer golang features.

**Comment by adamruzicka** [comment]
Now that https://github.com/theforeman/foreman-packaging/pull/11110 is merged, does this need any changes or can it go in as-is?

**Comment by ekohl** [comment]
I think it can be merged as-is. You may want to squash the commits. You can also add the SLES target to match what we build in our client repos, but I'll leave that up to you.

**Comment by adamruzicka** [comment]
Thank you @ekohl !

**Pull request merged**
