### PR TITLE
Cancel

### PR DESCRIPTION
**Pull request by adamruzicka**
Companion PR to https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/66

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Cool stuff! Looks good to me.
Only thing is that the original author lausily didn't set any testing framework and this will get it on the edge where it would be actually quite usefull. What are your thoughts on that?

**Comment by ezr-ondrej** [comment]
Food for though: would it be good to think about persistence cross service restart?
Or should we cancel/wait on the running jobs on restarts?

**Review by ezr-ondrej — COMMENTED** [review]
Great job on the testing ! :+1:

**Comment by adamruzicka** [comment]
I'd say this is good to go for now, please let me squash before merging.

**Review by ezr-ondrej — APPROVED** [review]
Lets get this in, LGTM :+1:

**Comment by ezr-ondrej** [comment]
:shipit: !

**Pull request merged**
